export const SET_API_TOKEN = "SET_API_TOKEN";
export const OPEN_TOKEN_MODAL = "OPEN_TOKEN_MODAL";

export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const OPEN_MODIFY_MODAL = "OPEN_MODIFY_MODAL";
export const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";

export const OPEN_CERT_LIST_MODAL = "OPEN_CERT_LIST_MODAL";
export const OPEN_RECERT_MODAL = "OPEN_RECERT_MODAL";
export const OPEN_DELETE_CERT_MODAL = "OPEN_DELETE_CERT_MODAL";

export const OPEN_MAIL_LIST_MODAL = "OPEN_MAIL_LIST_MODAL";
export const OPEN_ADD_MAIL_MODAL = "OPEN_ADD_MAIL_MODAL";
export const OPEN_DELETE_MAIL_MODAL = "OPEN_DELETE_MAIL_MODAL";

export const SET_ALERT_MODAL_MSG = "SET_ALERT_MODAL_MSG";
export const SET_REFRESH_PROJECT = "SET_REFRESH_PROJECT";
export const SET_REFRESH_CERT = "SET_REFRESH_CERT";
export const SET_REFRESH_EMAIL = "SET_REFRESH_EMAIL";






